### ISSUE TITLE
Error: stylelint v3+ requires plugins to expose a ruleName

### ISSUE THREAD

**Issue by webkonstruktor** [stormwarning/stylelint-config-recess-order#25]
Error: stylelint v3+ requires plugins to expose a ruleName. The plugin "/home/user/project/node_modules/stylelint-config-recess-order/index.js" is not doing this, so will not work with stylelint v3+. Please file an issue with the plugin.

**Comment by stormwarning** [comment]
You probably want to `extend` this in your stylelint config, instead of using it as a plugin:

```js
"extends": "stylelint-config-recess-order"
```

**Comment by stormwarning** [comment]
Closing this — feel free to reopen if you're still getting errors using the config 👍
