### ISSUE TITLE
`appearance` property is missing

### ISSUE THREAD

**Issue by robsonsobral** [stormwarning/stylelint-config-recess-order#322]
[`appearance`](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance) is missing. Do you accept a PR? Any suggestion on where to put it?

Thank you!

**Comment by stormwarning** [comment]
Adding it to the "Accessibility & Interactions." section makes the most sense to me. I know this is an old issue, but I can make this change after a bit of cleanup.
