### ISSUE TITLE
mask properties

### ISSUE THREAD

**Issue by robsonsobral** [stormwarning/stylelint-config-recess-order#347]
Hi! Thank you for keeping RECESS order alive!

Is it possible to add the [mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) related properties?

- `mask`
- `mask-image`
- `mask-mode`
- `mask-repeat`
- `mask-position`
- `mask-clip`
- `mask-origin`
- `mask-size`
- `mask-composite`

I guess they could follow the background properties.

**Comment by robsonsobral** [comment]
Oh, I forgot the [`mask-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border) properties!

- `mask-border`
- `mask-border-mode`
- `mask-border-outset`
- `mask-border-repeat`
- `mask-border-slice`
- `mask-border-source`
- `mask-border-width`

**Comment by stormwarning** [comment]
Hey, apologies for the late response; glad you find it useful though! I'll add these properties to the next batch 👍

**Comment by stormwarning** [comment]
According to the W3C:

> The [mask](https://drafts.fxtf.org/css-masking/#propdef-mask) shorthand also resets [mask-border](https://drafts.fxtf.org/css-masking/#propdef-mask-border) to its initial value. It is therefore recommended that authors use the mask shorthand, rather than other shorthands or the individual properties, to override any mask settings earlier in the cascade. This will ensure that mask-border has also been reset to allow the new styles to take effect.

So I've added `mask-border` properties *before* `mask` — if you're familiar with this properties, let me know if this would be problematic in practice.
