### ISSUE TITLE
flex-flow and flex-direction are backwards

### ISSUE THREAD

**Issue by simon-paris** [stormwarning/stylelint-config-recess-order#385]
`flex-direction` is overridden by `flex-flow` , they should never appear in that order.

Placing these two properties in that order will always cause this error: `Unexpected shorthand "flex-flow" after "flex-direction" (declaration-block-no-shorthand-property-overrides)`. And applying the autofix in this case could break things.

**Comment by stormwarning** [comment]
Nice catch! I'll try have a fix out for that this weekend
