### ISSUE TITLE
Use recess config as a plugin

### ISSUE THREAD

**Issue by paesku** [stormwarning/stylelint-config-recess-order#7]
Would be awesome if this module could be used as a normal stylelint plugin: https://stylelint.io/developer-guide/plugins/

**Comment by stormwarning** [comment]
Thanks for the suggestion! What would you need this config to be a plugin for though? It's just a specific set of Stylelint rules to be extended in one's own config and doesn't provide any new rules/options.

**Comment by paesku** [comment]
well you're right. never mind, I just went the wrong path to make it work 🤒 and tried is as a plugin.
